# Generated by Django 4.0.4 on 2022-05-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='quantity',
        ),
    ]
