# Generated by Django 4.0.4 on 2022-07-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_building_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='building',
        ),
    ]
