# Generated by Django 4.0.4 on 2022-07-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
