# Generated by Django 4.0.4 on 2022-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
